name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /angular-learning-practice/ --output-path docs

      # 🔥 Fix: Move browser/* to docs root
      - name: Move build files
        run: |
          cp -r docs/browser/* docs/
          rm -rf docs/browser

      # 🔥 Now index.html exists in docs/
      - name: Copy index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
