name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # change if your branch is 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /angular-learning-practice/

      - name: Copy index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs



          